version: '3.8'

services:
  backend:
    build: C:/Users/louis/OneDrive - Fondation EPF/DATA/DevOps/simpleapi
    environment:
      - DATABASE_URL=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
      - ENV=production
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  httpd-server:
    build: ./httpd-server
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./httpd-server/conf:/usr/local/apache2/conf:ro
      - ./httpd-server/logs:/usr/local/apache2/logs

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
