# Ajoute ce job à ton fichier main.yml après le job test-backen
build-and-push-docker-image:
  needs: test-backend
  runs-on: ubuntu-24.04

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USER_NAME_DOCKER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push backend
      uses: docker/build-push-action@v6
      with:
        context: ./simpleapi  # chemin vers Dockerfile backend
        push: true
        tags: ${{ secrets.USER_NAME_DOCKER }}/tp-devops-simple-api:latest

    - name: Build image and push database
      uses: docker/build-push-action@v6
      with:
        context: ./database  # adapte selon l’arborescence réelle
        push: true
        tags: ${{ secrets.USER_NAME_DOCKER }}/tp-devops-database:latest

    - name: Build image and push httpd
      uses: docker/build-push-action@v6
      with:
        context: ./httpd  # adapte selon l’arborescence réelle
        push: true
        tags: ${{ secrets.USER_NAME_DOCKER }}/tp-devops-httpd:latest
