name: CI DevOps 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-and-publish-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean verify --file ./simpleapi/pom.xml

      # Nouvelle étape : setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Connexion sécurisée à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER_NAME_DOCKER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construction et push de l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./simpleapi
          push: true
          tags: ${{ secrets.USER_NAME_DOCKER }}/simple-api:latest
